-- Создание таблицы TARIFS
CREATE TABLE TARIFS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COST DECIMAL(15, 2)
);

-- Создание таблицы CLIENTS
CREATE TABLE CLIENTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PLACE_OF_BIRTH VARCHAR(255),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(255),
    PASSPORT VARCHAR(255)
);

-- Создание таблицы PRODUCT_TYPE
CREATE TABLE PRODUCT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BEGIN_DATE DATE,
    END_DATE DATE,
    TARIF_REF INT REFERENCES TARIFS(ID)
);

-- Создание таблицы PRODUCTS
CREATE TABLE PRODUCTS (
    ID SERIAL PRIMARY KEY,
    PRODUCT_TYPE_ID INT REFERENCES PRODUCT_TYPE(ID),
    NAME VARCHAR(255) NOT NULL,
    CLIENT_REF INT REFERENCES CLIENTS(ID),
    OPEN_DATE DATE,
    CLOSE_DATE DATE
);

-- Создание таблицы ACCOUNTS
CREATE TABLE ACCOUNTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SALDO DECIMAL(15, 2) DEFAULT 0,
    CLIENT_REF INT REFERENCES CLIENTS(ID),
    OPEN_DATE DATE,
    CLOSE_DATE DATE,
    PRODUCT_REF INT REFERENCES PRODUCTS(ID),
    ACC_NUM VARCHAR(255) UNIQUE
);

-- Создание таблицы RECORDS
CREATE TABLE RECORDS (
    ID SERIAL PRIMARY KEY,
    DT BOOLEAN NOT NULL,
    ACC_REF INT REFERENCES ACCOUNTS(ID),
    OPER_DATE DATE,
    SUM DECIMAL(15, 2)
);